//! Mosquitto ACL generation from installed-plugin manifests (M5a W3 — debt #8).
//!
//! Replaces the M1-era `pattern readwrite #` permissive ACL with one
//! that grants the host's MQTT user exactly the union of subscribe +
//! publish topics declared across every installed plugin's manifest —
//! and nothing else. Plugins running under the WASM host go through
//! the shared `iot-plugin-host` MQTT connection, so it's the host's
//! cert CN (mapped to a username via Mosquitto's
//! `use_identity_as_username true`) that the ACL needs to authorise.
//!
//! The generated file shape (Mosquitto 2.0 grammar):
//!
//! ```text
//! # Generated by `iotctl mosquitto regen-acl` — do not edit.
//! # Plugins: demo-echo (0.1.0), zigbee2mqtt-adapter (0.3.0)
//!
//! user iot-plugin-host
//! topic read  zigbee2mqtt/+
//! topic write zigbee2mqtt/cmd/+
//! ```
//!
//! Mosquitto 2.0 denies all pub/sub for authenticated users absent an
//! explicit `topic` rule, so every plugin's filters must appear under
//! the matching `user` block or the broker drops the messages
//! silently.
//!
//! When zero plugins are installed the file emits no `topic` rules.
//! That intentionally yields a "deny everything" ACL for the host
//! user — fail-closed, the host won't accidentally publish on a
//! topic no plugin asked about.

use std::fmt::Write as _;

use crate::manifest::Manifest;

/// Build the ACL file body for a single Mosquitto user.
///
/// `user` is the Mosquitto username (typically the host's mTLS cert
/// CN); `manifests` is the set of installed plugin manifests whose
/// `mqtt.subscribe` + `mqtt.publish` allow-lists union into the
/// granted ACL.
///
/// Order is deterministic: manifests sorted by id; within each
/// manifest, subscribe filters first then publish, both in the order
/// the manifest declared (which the YAML parser preserves).
#[must_use]
pub fn generate(user: &str, manifests: &[&Manifest]) -> String {
    let mut sorted: Vec<&&Manifest> = manifests.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    let plugins_summary = if sorted.is_empty() {
        "(none installed)".to_owned()
    } else {
        sorted
            .iter()
            .map(|m| format!("{} ({})", m.id, m.version))
            .collect::<Vec<_>>()
            .join(", ")
    };

    let mut out = String::new();
    out.push_str("# Generated by `iotctl mosquitto regen-acl` — do not edit.\n");
    out.push_str("# Re-run after every `iotctl plugin install` / `uninstall`.\n");
    let _ = writeln!(out, "# Plugins: {plugins_summary}");
    out.push('\n');
    let _ = writeln!(out, "user {user}");

    if sorted.is_empty() {
        // Mosquitto with no `topic` lines means "deny everything for
        // this user". Document the intent so an operator scanning the
        // file doesn't think the generator broke.
        out.push_str("# (no plugins installed → no topics granted; fail-closed)\n");
        return out;
    }

    for m in sorted {
        // Per-plugin section header so the operator can grep
        // `# plugin: zigbee2mqtt-adapter` and see exactly what
        // capabilities it pulled in.
        let _ = writeln!(
            out,
            "\n# plugin: {} ({}) — {} subscribe, {} publish",
            m.id,
            m.version,
            m.capabilities.mqtt.subscribe.len(),
            m.capabilities.mqtt.publish.len(),
        );
        for filter in &m.capabilities.mqtt.subscribe {
            let _ = writeln!(out, "topic read  {filter}");
        }
        for topic in &m.capabilities.mqtt.publish {
            let _ = writeln!(out, "topic write {topic}");
        }
    }
    out
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::capabilities::{CapabilityMap, MqttCapabilities};
    use crate::manifest::{Manifest, Resources};

    fn manifest_with_mqtt(id: &str, version: &str, subs: &[&str], pubs: &[&str]) -> Manifest {
        Manifest {
            schema_version: 1,
            id: id.to_owned(),
            name: id.to_owned(),
            version: version.to_owned(),
            description: String::new(),
            runtime: "wasm-component".to_owned(),
            entrypoint: "plugin.wasm".to_owned(),
            capabilities: CapabilityMap {
                mqtt: MqttCapabilities {
                    publish: pubs.iter().map(|s| (*s).to_owned()).collect(),
                    subscribe: subs.iter().map(|s| (*s).to_owned()).collect(),
                    bridge: Vec::new(),
                },
                ..Default::default()
            },
            resources: Resources::default(),
            signatures: Vec::new(),
        }
    }

    #[test]
    fn empty_plugin_set_deny_closes() {
        let body = generate("iot-plugin-host", &[]);
        assert!(body.contains("user iot-plugin-host"));
        assert!(
            !body.contains("topic "),
            "no topic rules → fail-closed deny: {body}"
        );
        assert!(body.contains("(no plugins installed"));
    }

    #[test]
    fn single_plugin_emits_subscribe_and_publish_rules() {
        let m = manifest_with_mqtt(
            "zigbee2mqtt-adapter",
            "0.3.0",
            &["zigbee2mqtt/+"],
            &["zigbee2mqtt/cmd/+"],
        );
        let body = generate("iot-plugin-host", &[&m]);

        assert!(body.contains("user iot-plugin-host"));
        assert!(body.contains("topic read  zigbee2mqtt/+"));
        assert!(body.contains("topic write zigbee2mqtt/cmd/+"));
        // Per-plugin section header makes the source grep-able.
        assert!(body.contains("# plugin: zigbee2mqtt-adapter (0.3.0)"));
    }

    #[test]
    fn multiple_plugins_unioned_and_id_sorted() {
        let z = manifest_with_mqtt("zigbee2mqtt-adapter", "0.3.0", &["zigbee2mqtt/+"], &[]);
        let s = manifest_with_mqtt("sdr433-adapter", "0.1.0", &["rtl_433/+"], &[]);
        let body = generate("iot-plugin-host", &[&z, &s]);

        // Both filters land in the file.
        assert!(body.contains("topic read  zigbee2mqtt/+"));
        assert!(body.contains("topic read  rtl_433/+"));

        // sdr433-adapter (s) sorts ahead of zigbee2mqtt-adapter (z).
        let sdr_pos = body.find("# plugin: sdr433-adapter").expect("sdr block");
        let z2m_pos = body
            .find("# plugin: zigbee2mqtt-adapter")
            .expect("z2m block");
        assert!(
            sdr_pos < z2m_pos,
            "alphabetical id order: sdr433 before z2m"
        );
    }

    #[test]
    fn plugin_with_no_mqtt_caps_emits_zero_topic_lines() {
        // demo-echo has no mqtt caps — generator should still include
        // the section header but emit no topic lines for it.
        let demo = manifest_with_mqtt("demo-echo", "0.1.0", &[], &[]);
        let body = generate("iot-plugin-host", &[&demo]);
        assert!(body.contains("# plugin: demo-echo (0.1.0) — 0 subscribe, 0 publish"));
        assert!(!body.contains("topic read"));
        assert!(!body.contains("topic write"));
    }

    #[test]
    fn plugins_summary_listed_in_header() {
        let z = manifest_with_mqtt("z", "1.0.0", &[], &[]);
        let a = manifest_with_mqtt("a", "0.5.0", &[], &[]);
        let body = generate("iot-plugin-host", &[&z, &a]);
        // Sorted: a then z.
        assert!(body.contains("# Plugins: a (0.5.0), z (1.0.0)"));
    }
}
