//! Wire-format constants and helpers.
//!
//! This crate will eventually host the Protobuf code generated by
//! `buf generate` (see `schemas/buf.gen.yaml`). During W1 we deliberately keep
//! codegen out of the build graph — developers don't need `protoc` to `cargo
//! build`. Hand-written mirrors of subject formats and header keys are enough
//! for every downstream crate to compile and for tests to exist.

#![forbid(unsafe_code)]

pub mod headers;
pub mod subjects;

pub use headers::*;
