//! Wire-format types (generated from `schemas/`) + hand-written helpers.
//!
//! The Protobuf/gRPC code is generated by `build.rs` via [`protox`] (no
//! `protoc` binary required). Hand-written subject builders and header key
//! constants live alongside so every publisher uses the same names.

#![forbid(unsafe_code)]

pub mod headers;
pub mod subjects;

pub use headers::*;

/// Generated Protobuf types.
///
/// Lints are silenced here because prost/tonic generate code we don't own.
#[allow(clippy::all, clippy::pedantic, clippy::nursery, missing_debug_implementations)]
pub mod iot {
    pub mod common {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/iot.common.v1.rs"));
        }
    }
    pub mod device {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/iot.device.v1.rs"));
        }
    }
    pub mod bus {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/iot.bus.v1.rs"));
        }
    }
    pub mod registry {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/iot.registry.v1.rs"));
        }
    }
}

// Shortcuts for the most-used names.
pub use iot::common::v1::{ErrorEnvelope, Ulid};
pub use iot::device::v1::{Device, Entity, ReadWrite, TrustLevel};
pub use iot::registry::v1::registry_service_client::RegistryServiceClient;
pub use iot::registry::v1::registry_service_server::{RegistryService, RegistryServiceServer};
